<!DOCTYPE html><html lang="hu"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ $content->effectiveSeoTitle() }}</title><meta name="description" content="{{ $content->effectiveSeoDescription() }}">
<meta name="robots" content="{{ $content->robots_index ? 'index' : 'noindex' }},{{ $content->robots_follow ? 'follow' : 'nofollow' }}">
<link rel="canonical" href="{{ $content->canonical_url ?: $content->publicUrl() }}">
<meta property="og:type" content="{{ $content->type === 'article' ? 'article' : 'website' }}"><meta property="og:title" content="{{ $content->social_title ?: $content->effectiveSeoTitle() }}"><meta property="og:description" content="{{ $content->social_description ?: $content->effectiveSeoDescription() }}"><meta property="og:url" content="{{ $content->canonical_url ?: $content->publicUrl() }}">
@if($content->social_image_path)<meta property="og:image" content="{{ asset('storage/'.$content->social_image_path) }}">@endif
<meta name="twitter:card" content="{{ $content->twitter_card }}"><meta name="twitter:title" content="{{ $content->social_title ?: $content->effectiveSeoTitle() }}"><meta name="twitter:description" content="{{ $content->social_description ?: $content->effectiveSeoDescription() }}">@if($content->social_image_path)<meta name="twitter:image" content="{{ asset('storage/'.$content->social_image_path) }}">@endif
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>$content->schema_type,'name'=>$content->title,'description'=>$content->effectiveSeoDescription(),'url'=>$content->canonical_url ?: $content->publicUrl(),'datePublished'=>$content->published_at?->toIso8601String(),'dateModified'=>$content->updated_at->toIso8601String()], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
<link rel="stylesheet" href="{{ asset('css/app-custom.css') }}"></head>
<body class="public-content-page">@include('layouts.navigation')
<main class="public-content-shell"><article><header><span>{{ $content->type === 'article' ? 'KwizzGo cikk' : 'KwizzGo információ' }}</span><h1>{{ $content->title }}</h1>@if($content->excerpt)<p>{{ $content->excerpt }}</p>@endif<div class="public-content-meta">@if($content->effective_at)<span>Hatályos: {{ $content->effective_at->format('Y. m. d.') }}</span>@endif<span>Verzió: {{ $content->version }}</span><span>Frissítve: {{ $content->updated_at->format('Y. m. d.') }}</span></div></header><div class="public-content-prose">{!! $content->content_html !!}</div></article>
@if($content->type === 'article' && $content->recommendedQuizzes->isNotEmpty())
<section class="article-recommended-quizzes" aria-labelledby="recommended-quizzes-title"><div class="article-recommended-heading"><span>Folytasd játékkal</span><h2 id="recommended-quizzes-title">A cikkhez ajánlott kvízek</h2></div><div class="article-recommended-grid">@foreach($content->recommendedQuizzes as $quiz)<a href="{{ auth()->check() ? route('quiz.setup', $quiz) : route('quizzes.share', $quiz) }}" class="article-recommended-card"><span class="article-recommended-cover" @if($quiz->cover_image) style="background-image:url('{{ asset('storage/'.$quiz->cover_image) }}')" @endif aria-hidden="true"></span><span class="article-recommended-copy"><small>{{ $quiz->category?->translated_name ?? $quiz->category?->name ?? 'KwizzGo kvíz' }}</small><strong>{{ $quiz->title }}</strong><em>{{ $quiz->questions_count }} kérdés · Játék indítása →</em></span></a>@endforeach</div></section>
@endif
<x-ad-slot position="content_horizontal" /></main>
<x-site-footer /></body></html>
