<!DOCTYPE html>
<html lang="hu"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $emailTemplate->exists ? 'Levél szerkesztése' : 'Új automatizált levél' }} | KwizzGo</title>@vite(['resources/css/app.css','resources/js/app.js','resources/js/content-editor.js'])<link rel="stylesheet" href="{{ asset('css/app-custom.css') }}"></head>
<body class="content-admin-page min-h-screen pb-12">@include('layouts.navigation')
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
    <div class="mb-6"><a href="{{ route('admin.email-templates.index') }}" class="text-sm font-bold text-purple-300">← E-mail sablonok</a><h1 class="mt-2 text-3xl font-black">{{ $emailTemplate->exists ? $emailTemplate->name : 'Új automatizált levél' }}</h1><p class="mt-2 text-slate-400">Gazdag tartalmú levél, amely a regisztráció után megadott napon egyszer jut el minden feliratkozott felhasználóhoz.</p></div>
    @if(session('success'))<div class="content-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="content-error"><strong>A mentés nem sikerült:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" enctype="multipart/form-data" data-content-editor-form action="{{ $emailTemplate->exists ? route('admin.email-templates.update',$emailTemplate) : route('admin.email-templates.store') }}">@csrf @if($emailTemplate->exists)@method('PATCH')@endif
        <div class="content-editor-layout"><section class="content-editor-main space-y-5">
            <div class="content-panel grid gap-4 md:grid-cols-2">
                <label><span>Belső sablonnév</span><input name="name" required maxlength="255" value="{{ old('name',$emailTemplate->name) }}" placeholder="Például: 3. napi kvízajánló"></label>
                <label><span>Kiküldés a regisztráció után</span><div class="flex items-center gap-2"><input type="number" name="days_after_registration" required min="0" max="3650" value="{{ old('days_after_registration',$emailTemplate->days_after_registration ?? 1) }}"><strong>nap</strong></div></label>
                <label class="md:col-span-2"><span>Levél tárgya</span><input name="subject" required maxlength="255" value="{{ old('subject',$emailTemplate->subject) }}" placeholder="Szia @{{username}}, ezt a kvízt neked ajánljuk!"></label>
                <label class="md:col-span-2"><span>Főcím</span><input name="heading" required maxlength="255" value="{{ old('heading',$emailTemplate->heading) }}" placeholder="Szia @{{username}}!"></label>
                <label class="md:col-span-2"><span>Fejléckép</span><input type="file" name="header_image" accept="image/jpeg,image/png,image/webp">@if($emailTemplate->header_image_path)<img src="{{ Storage::disk('public')->url($emailTemplate->header_image_path) }}" class="mt-3 max-h-48 rounded-xl" alt="Jelenlegi fejléckép">@endif</label>
            </div>
            <div class="content-panel"><div class="content-editor-toolbar" data-editor-toolbar>
                @foreach([['bold','B'],['italic','I'],['underline','U'],['strike','S'],['h2','H2'],['h3','H3'],['bulletList','• Lista'],['orderedList','1. Lista'],['blockquote','Idézet'],['link','Link'],['alignLeft','Bal'],['alignCenter','Közép'],['alignRight','Jobb'],['table','Táblázat'],['undo','↶'],['redo','↷']] as [$command,$label])<button type="button" data-editor-command="{{ $command }}">{{ $label }}</button>@endforeach
                <button type="button" data-editor-image>Kép</button><input type="file" data-editor-image-input accept="image/jpeg,image/png,image/webp,image/gif" hidden>
            </div><div class="content-tiptap-editor" data-content-editor data-upload-url="{{ route('admin.email-templates.upload-image') }}"></div><input type="hidden" name="content_json" data-content-json><input type="hidden" name="content_html" data-content-html><script type="application/json" data-initial-content>{!! json_encode(old('content_json') ? json_decode(old('content_json'),true) : $emailTemplate->content_json, JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) !!}</script>@if(!$emailTemplate->content_json && $emailTemplate->content_html)<template data-initial-html>{!! $emailTemplate->content_html !!}</template>@endif</div>
            <div class="content-panel grid gap-5 md:grid-cols-2"><label><span>Ajánlott kvízek</span><select name="recommended_quiz_ids[]" multiple size="8">@foreach($quizzes as $quiz)<option value="{{ $quiz->id }}" @selected(in_array($quiz->id,old('recommended_quiz_ids',$emailTemplate->recommended_quiz_ids ?? [])))>{{ $quiz->title }}</option>@endforeach</select></label><label><span>Ajánlott tartalmak</span><select name="recommended_content_ids[]" multiple size="8">@foreach($contents as $content)<option value="{{ $content->id }}" @selected(in_array($content->id,old('recommended_content_ids',$emailTemplate->recommended_content_ids ?? [])))>{{ $content->title }}</option>@endforeach</select></label><p class="md:col-span-2 text-sm text-slate-400">Ctrl (Macen ⌘) segítségével több ajánlást is kijelölhetsz. Ezek külön, kattintható blokkokként kerülnek a levélbe.</p></div>
            <div class="content-panel grid gap-4 md:grid-cols-2"><label><span>Fő gomb felirata</span><input name="button_text" maxlength="100" value="{{ old('button_text',$emailTemplate->button_text) }}" placeholder="Folytatom a játékot"></label><label class="md:col-span-2"><span>Záró szöveg</span><textarea name="footer" rows="3">{{ old('footer',$emailTemplate->footer) }}</textarea></label></div>
        </section><aside class="content-editor-sidebar space-y-5"><div class="content-panel"><h2>Kiküldés</h2><label class="flex-row items-center gap-3"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$emailTemplate->is_active))><span>Automatika aktív</span></label><label class="mt-4 flex-row items-center gap-3"><input type="checkbox" name="include_progress" value="1" @checked(old('include_progress',$emailTemplate->include_progress ?? true))><span>„Így állsz” blokk beillesztése</span></label><p class="mt-3 text-xs text-slate-400">A blokk a címzett saját kvízeit, eredményeit és folytatási linkjeit mutatja.</p><button class="content-primary-button mt-5 w-full">Mentés</button></div>@if($emailTemplate->exists)<div class="content-panel"><h2>Tesztküldés</h2><p class="text-sm text-slate-400">A személyre szabott előnézet a megadott címre érkezik.</p><label class="mt-4"><span>Címzett e-mail-címe</span><input type="email" name="test_email" form="campaign-test-form" value="{{ old('test_email', config('services.email_templates.test_recipient') ?: auth()->user()->email) }}" maxlength="255" placeholder="teszt@example.com"></label><p class="mt-2 text-xs text-slate-400">Felülírja az ENV-ben megadott tesztcímet.</p><button type="submit" form="campaign-test-form" class="content-secondary-button mt-4 w-full">Tesztlevél küldése</button></div>@endif<div class="content-panel"><h2>Változók</h2><code class="block">@{{username}}</code><code class="block">@{{email}}</code></div></aside></div>
    </form>@if($emailTemplate->exists)<form id="campaign-test-form" method="POST" action="{{ route('admin.email-templates.test',$emailTemplate) }}">@csrf</form>@endif
</main></body></html>
