<!DOCTYPE html><html lang="hu"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>E-mail sablonok | KwizzGo</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900">@include('layouts.navigation')
<main class="mx-auto max-w-7xl px-4 py-8 sm:px-6">
<header class="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><p class="text-sm font-black uppercase tracking-widest text-amber-300">Adminisztracio</p><h1 class="mt-2 text-3xl font-black">E-mail sablonok</h1><p class="mt-3 text-slate-300">Hasznalhato valtozok: <code>@{{username}}</code> es <code>@{{email}}</code>. Link: <code>[Megjeleno szoveg](https://kwizzgo.com/celoldal)</code>. A hitelesitesi linket a rendszer illeszti be.</p></header>
@if(session('success'))<div class="mt-5 rounded-xl bg-emerald-100 p-4 font-bold text-emerald-800">{{ session('success') }}</div>@endif
@if(session('error'))<div class="mt-5 rounded-xl bg-red-100 p-4 font-bold text-red-800">{{ session('error') }}</div>@endif
<div class="mt-6 grid gap-6 lg:grid-cols-2">@foreach($templates as $template)
<section class="rounded-3xl bg-white p-6 shadow-xl"><div class="flex items-center justify-between gap-3"><h2 class="text-2xl font-black">{{ $template->name }}</h2><span class="rounded-full px-3 py-1 text-xs font-black {{ $template->is_active ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-200 text-slate-600' }}">{{ $template->is_active ? 'Aktiv' : 'Inaktiv' }}</span></div>
<form method="POST" action="{{ route('admin.email-templates.update',$template) }}" class="mt-5 space-y-4">@csrf @method('PATCH')
<label class="block font-bold">Targy<input name="subject" value="{{ old('subject',$template->subject) }}" required maxlength="255" class="mt-1 w-full rounded-xl border-slate-300"></label>
<label class="block font-bold">Cimsor<input name="heading" value="{{ old('heading',$template->heading) }}" required maxlength="255" class="mt-1 w-full rounded-xl border-slate-300"></label>
<label class="block font-bold">Level szovege<textarea name="body" required rows="7" class="mt-1 w-full rounded-xl border-slate-300">{{ old('body',$template->body) }}</textarea><span class="mt-1 block text-xs font-normal text-slate-500">Egy Enter uj sort, ket Enter lathato ures sort keszit. Link: [Kvizkatalogus](https://kwizzgo.com/quizzes)</span></label>
<label class="block font-bold">Gomb felirata<input name="button_text" value="{{ old('button_text',$template->button_text) }}" maxlength="100" class="mt-1 w-full rounded-xl border-slate-300"></label>
<label class="block font-bold">Zaro szoveg<textarea name="footer" rows="3" class="mt-1 w-full rounded-xl border-slate-300">{{ old('footer',$template->footer) }}</textarea></label>
@if($template->key === \App\Models\EmailTemplate::WELCOME)<label class="flex items-center gap-3 font-bold"><input type="checkbox" name="is_active" value="1" @checked($template->is_active) class="rounded"> Welcome level aktiv</label>@else<p class="text-sm font-bold text-emerald-700">A dupla opt-in hitelesito level mindig aktiv.</p>@endif<button class="rounded-xl bg-indigo-700 px-5 py-3 font-black text-white">Sablon mentese</button></form>
<form method="POST" action="{{ route('admin.email-templates.test',$template) }}" class="mt-3">@csrf<button class="rounded-xl border border-amber-500 px-5 py-3 font-black text-amber-700">Tesztlevel kuldese nekem</button></form>
<div class="mt-5 rounded-2xl border bg-slate-50 p-5"><div class="text-xs font-black uppercase text-slate-500">Elozetes</div><div class="mt-3 font-black">{{ $template->render($template->heading,auth()->user()) }}</div><div class="prose prose-slate mt-2 max-w-none text-slate-700">{!! \Illuminate\Support\Str::markdown($template->render($template->body,auth()->user()), ['html_input' => 'strip', 'allow_unsafe_links' => false, 'renderer' => ['soft_break' => "<br>\n"]]) !!}</div>@if($template->button_text)<div class="mt-4 inline-block rounded-lg bg-amber-400 px-4 py-2 font-black">{{ $template->render($template->button_text,auth()->user()) }}</div>@endif<div class="prose prose-sm prose-slate mt-4 max-w-none text-slate-500">{!! \Illuminate\Support\Str::markdown($template->render($template->footer ?? '',auth()->user()), ['html_input' => 'strip', 'allow_unsafe_links' => false, 'renderer' => ['soft_break' => "<br>\n"]]) !!}</div></div></section>
@endforeach</div></main></body></html>
