<!DOCTYPE html><html lang="hu"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $template->render($template->subject,$user) }}</title></head>
<body style="margin:0;background:#f1f5f9;font-family:Arial,sans-serif;color:#172033"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f1f5f9;padding:24px 10px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:680px;background:#fff;border-radius:24px;overflow:hidden">
@if($headerImageUrl)<tr><td><img src="{{ $headerImageUrl }}" alt="" width="680" style="display:block;width:100%;height:auto"></td></tr>@endif
<tr><td style="padding:32px"><div style="font-size:13px;font-weight:800;letter-spacing:2px;color:#7c3aed">KWIZZGO</div><h1 style="margin:10px 0 20px;font-size:30px;color:#17112c">{{ $template->render($template->heading,$user) }}</h1><div style="font-size:16px;line-height:1.65">{!! $html !!}</div>
@if($quizzes->isNotEmpty())<h2 style="margin-top:30px">Neked ajánlott kvízek</h2>@foreach($quizzes as $quiz)<p style="margin:10px 0;padding:14px;background:#f5f3ff;border-radius:12px"><a href="{{ route('quizzes.share',$quiz) }}" style="font-weight:800;color:#6d28d9;text-decoration:none">{{ $quiz->title }} →</a></p>@endforeach @endif
@if($contents->isNotEmpty())<h2 style="margin-top:30px">Újdonságok</h2>@foreach($contents as $content)<p style="margin:10px 0;padding:14px;background:#fffbeb;border-radius:12px"><a href="{{ $content->publicUrl() }}" style="font-weight:800;color:#92400e;text-decoration:none">{{ $content->title }} →</a></p>@endforeach @endif
@if($template->include_progress)<div style="margin-top:30px;padding:22px;background:#17112c;border-radius:16px;color:#fff"><h2 style="margin:0 0 8px;color:#fbbf24">Így állsz most</h2>@forelse($quizResults as $result)@php($accuracy=$result->answers ? (int)round($result->correct_answers/$result->answers*100):0)<div style="padding:12px 0;border-top:1px solid #39304f"><strong>{{ $result->title }}</strong><br><span style="color:#d8d2e5">{{ $result->answers }} kérdés · {{ $result->correct_answers }} helyes · {{ $accuracy }}%</span><br><a href="{{ route('quiz.setup',['quiz'=>$result->slug ?: $result->id]) }}" style="color:#fbbf24;font-weight:800">Folytatom →</a></div>@empty<p style="color:#d8d2e5">Még nincs eredményed – válassz egy ajánlott kvízt, és kezdd el a játékot!</p>@endforelse</div>@endif
@if($template->button_text)<p style="margin:30px 0;text-align:center"><a href="{{ route('quizzes.index') }}" style="display:inline-block;padding:14px 24px;background:#fbbf24;border-radius:10px;color:#17112c;font-weight:900;text-decoration:none">{{ $template->render($template->button_text,$user) }}</a></p>@endif
@if($template->footer)<div style="margin-top:24px;color:#64748b;font-size:13px;line-height:1.5">{{ $template->render($template->footer,$user) }}</div>@endif
@if($trackingUrl)<img src="{{ $trackingUrl }}" width="1" height="1" alt="" style="display:block;width:1px;height:1px;border:0" aria-hidden="true">@endif
<p style="margin-top:28px;font-size:12px;color:#94a3b8">Ezt a levelet a KwizzGo értesítési beállításaid alapján kaptad. A kvízajánló leveleket a profilodban bármikor kikapcsolhatod.</p></td></tr></table></td></tr></table></body></html>
